apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: USER_SERVICE_HOST
              value: user-service

            - name: AUTH_DEV_MODE
              value: "true"

            - name: SECURITY_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chatapp-secret
                  key: SECURITY_JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: chatapp
spec:
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081